// 2025/aug/shop/resources/js/pages/Auth/Login.tsx
// resources/js/Pages/Auth/Login.tsx
import { Head, useForm } from '@inertiajs/react';
import { motion } from 'framer-motion';
import { FormEvent } from 'react';

export default function Login({ flash }) {
    const { data, setData, post, processing, errors } = useForm({
        email: '',
    });

    const handleSubmit = (e: FormEvent) => {
        e.preventDefault();
        post(route('magic-link.send'));
    };

    // Floating circles data
    const circles = [
        { size: 200, top: '20%', left: '10%', delay: 0 },
        { size: 300, top: '60%', right: '15%', delay: 2 },
        { size: 150, bottom: '15%', left: '25%', delay: 4 },
    ];
    const isValidEmail = (email: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

    return (
        <>
            <Head title="Login" />

            {/* Background gradient */}
            <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-gradient-to-br from-green-500 to-green-700 px-4 py-12 sm:px-6 lg:px-8">
                {/* Floating circles */}
                {circles.map((c, i) => (
                    <motion.div
                        key={i}
                        className="absolute rounded-full bg-white/10 backdrop-blur-xl"
                        style={{
                            width: c.size,
                            height: c.size,
                            top: c.top,
                            left: c.left,
                            right: c.right,
                            bottom: c.bottom,
                        }}
                        animate={{ y: [0, -30, 0], scale: [1, 1.05, 1], opacity: [0.6, 1, 0.6] }}
                        transition={{ duration: 6, repeat: Infinity, delay: c.delay }}
                    />
                ))}

                {/* Card */}
                <motion.div
                    initial={{ y: 50, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ duration: 0.8 }}
                    className="relative z-10 w-full max-w-md"
                >
                    <div className="rounded-2xl bg-white/20 p-8 shadow-2xl backdrop-blur-lg">
                        <h2 className="mb-6 text-center text-3xl font-extrabold text-white">POTBELLY</h2>

                        {/* Success Message */}
                        {flash?.success && (
                            <div className="mb-4 rounded-lg border border-green-400 bg-green-100 px-4 py-3 text-green-700">{flash.success}</div>
                        )}

                        <form className="space-y-5" onSubmit={handleSubmit}>
                            {/* Email */}
                            <div>
                                <input
                                    id="email"
                                    name="email"
                                    type="email"
                                    placeholder="Email address"
                                    required
                                    className="w-full rounded-xl border border-white/30 bg-white/20 px-4 py-3 text-white placeholder-gray-200 focus:border-green-400 focus:ring-green-400 focus:outline-none"
                                    value={data.email}
                                    onChange={(e) => setData('email', e.target.value)}
                                />
                                {errors.email && <p className="mt-1 text-sm text-red-300">{errors.email}</p>}
                            </div>

                            {/* Submit */}
                            <motion.button
                                whileTap={{ scale: 0.95 }}
                                type="submit"
                                disabled={processing || !isValidEmail(data.email)} // 🚀 check format
                                className="flex w-full justify-center rounded-xl bg-gradient-to-r from-green-500 to-green-600 px-4 py-3 font-medium text-white shadow-lg hover:from-green-600 hover:to-green-700 disabled:cursor-not-allowed disabled:opacity-50"
                            >
                                {processing ? 'Sending Login Link...' : 'Send Login Link'}
                            </motion.button>
                        </form>
                    </div>
                </motion.div>
            </div>
        </>
    );
}

// 2025/sept/shop/resources/js/pages/Login.vue
<script setup lang="ts">
import { Head, useForm } from '@inertiajs/vue3';

const props = defineProps<{
    flash?: { success?: string };
}>();

const form = useForm({
    email: '',
});

const isValidEmail = (email: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

const handleSubmit = () => {
    form.post(route('magic-link.send'));
};

// Floating circles data
const circles = [
    { size: 200, top: '20%', left: '10%', delay: 0 },
    { size: 300, top: '60%', right: '15%', delay: 2 },
    { size: 150, bottom: '15%', left: '25%', delay: 4 },
];
</script>

<template>
    <Head title="Login" />

    <div
        class="relative flex min-h-screen items-center justify-center overflow-hidden bg-gradient-to-br from-green-500 to-green-700 px-4 py-12 sm:px-6 lg:px-8"
    >
        <!-- Floating circles -->
        <div
            v-for="(c, i) in circles"
            :key="i"
            class="absolute rounded-full bg-white/10 backdrop-blur-xl"
            :style="{
                width: c.size + 'px',
                height: c.size + 'px',
                top: c.top,
                left: c.left,
                right: c.right,
                bottom: c.bottom,
                animationDelay: c.delay + 's',
            }"
            class="animate-floating"
        />

        <!-- Card -->
        <div
            v-motion
            :initial="{ y: 50, opacity: 0 }"
            :enter="{ y: 0, opacity: 1, transition: { duration: 0.8 } }"
            class="relative z-10 w-full max-w-md"
        >
            <div class="rounded-2xl bg-white/20 p-8 shadow-2xl backdrop-blur-lg">
                <h2 class="mb-6 text-center text-3xl font-extrabold text-white">POTBELLY</h2>

                <!-- Success Message -->
                <div v-if="props.flash?.success" class="mb-4 rounded-lg border border-green-400 bg-green-100 px-4 py-3 text-green-700">
                    {{ props.flash.success }}
                </div>

                <form class="space-y-5" @submit.prevent="handleSubmit">
                    <!-- Email -->
                    <div>
                        <input
                            id="email"
                            name="email"
                            type="email"
                            placeholder="Email address"
                            required
                            class="w-full rounded-xl border border-white/30 bg-white/20 px-4 py-3 text-white placeholder-gray-200 focus:border-green-400 focus:ring-green-400 focus:outline-none"
                            v-model="form.email"
                        />
                        <p v-if="form.errors.email" class="mt-1 text-sm text-red-300">
                            {{ form.errors.email }}
                        </p>
                    </div>

                    <!-- Submit -->
                    <button
                        type="submit"
                        :disabled="form.processing || !isValidEmail(form.email)"
                        class="flex w-full justify-center rounded-xl bg-gradient-to-r from-green-500 to-green-600 px-4 py-3 font-medium text-white shadow-lg hover:from-green-600 hover:to-green-700 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                        {{ form.processing ? 'Sending Login Link...' : 'Send Login Link' }}
                    </button>
                </form>
            </div>
        </div>
    </div>
</template>

<style>
@keyframes floating {
    0%,
    100% {
        transform: translateY(0) scale(1);
        opacity: 0.6;
    }
    50% {
        transform: translateY(-30px) scale(1.05);
        opacity: 1;
    }
}
.animate-floating {
    animation: floating 6s infinite;
}
</style>
